<a href="https://colab.research.google.com/github/pragatisachan/ProjectChalenge1/blob/main/Placement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PLACEMENT**

**OBJECTIVE - The Placement Prediction System, where student can
estimate their chances of securing on-campus placements, considering several parameters such as  CGPA, IQ and more. Students can estimate their results within few clicks by submitting short form. The website usage the machine learning model to analyze the input parameters. The dataset downloaded from the https://github.com/YBI-Foundation/Dataset for testing**


# **Import Library**

In [1]:
import pandas as pd
import numpy as np

# **Import CSV as DataSet**

In [4]:
df = pd.read_csv("https://github.com/YBI-Foundation/Dataset/raw/main/Placement.csv" )
df.head()

Student_ID  CGPA   IQ  Placement
0           1   6.8  123          1
1           2   5.9  106          0
2           3   5.3  121          0
3           4   7.4  132          1
4           5   5.8  142          0

# **Get Information Data**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Student_ID  100 non-null    int64  
 1   CGPA        100 non-null    float64
 2   IQ          100 non-null    int64  
 3   Placement   100 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 3.2 KB


In [6]:
df.describe()

Student_ID        CGPA          IQ   Placement
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      1.000000    3.300000   37.000000    0.000000
25%     25.750000    5.075000  101.500000    0.000000
50%     50.500000    6.000000  127.500000    0.500000
75%     75.250000    6.900000  149.000000    1.000000
max    100.000000    8.500000  233.000000    1.000000

In [7]:
df.isnull()

Student_ID   CGPA     IQ  Placement
0        False  False  False      False
1        False  False  False      False
2        False  False  False      False
3        False  False  False      False
4        False  False  False      False
..         ...    ...    ...        ...
95       False  False  False      False
96       False  False  False      False
97       False  False  False      False
98       False  False  False      False
99       False  False  False      False

[100 rows x 4 columns]

# **Spliting into Dependent  y and Independent X**

In [8]:
X = df[['CGPA' , 'IQ']]

In [9]:
y = df['Placement']

In [10]:
y

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: Placement, Length: 100, dtype: int64

# **Standardize Indepdent Features**

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X.shape

(100, 2)

# **Train Test Split**

In [12]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.3 , random_state = 2529)
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((70, 2), (30, 2), (70,), (30,))

# **Get Model Train**

In [14]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train , y_train)

LogisticRegression()

# **Get Model Predictions**

In [15]:
y_pred = lr.predict(X_test)
y_pred.shape
y_pred

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1])

# **Get Probab of Each Predicted Class**

In [16]:
lr.predict_proba(X_test)

array([[0.14625283, 0.85374717],
       [0.93627665, 0.06372335],
       [0.31225355, 0.68774645],
       [0.85921675, 0.14078325],
       [0.55859556, 0.44140444],
       [0.59855708, 0.40144292],
       [0.03230864, 0.96769136],
       [0.36854121, 0.63145879],
       [0.00221892, 0.99778108],
       [0.94998577, 0.05001423],
       [0.71998293, 0.28001707],
       [0.06678211, 0.93321789],
       [0.24280142, 0.75719858],
       [0.9766201 , 0.0233799 ],
       [0.38513856, 0.61486144],
       [0.28100947, 0.71899053],
       [0.36919946, 0.63080054],
       [0.9505204 , 0.0494796 ],
       [0.66663238, 0.33336762],
       [0.84791247, 0.15208753],
       [0.88526065, 0.11473935],
       [0.00321788, 0.99678212],
       [0.03402257, 0.96597743],
       [0.12203804, 0.87796196],
       [0.07455692, 0.92544308],
       [0.96120589, 0.03879411],
       [0.95991072, 0.04008928],
       [0.43982882, 0.56017118],
       [0.91414187, 0.08585813],
       [0.21780653, 0.78219347]])

# **Get Model Evalution**

In [17]:
from sklearn.metrics import confusion_matrix , classification_report

In [18]:
confusion_matrix(y_test , y_pred)

array([[12,  0],
       [ 2, 16]])

In [19]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.86      1.00      0.92        12
           1       1.00      0.89      0.94        18

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.93        30
weighted avg       0.94      0.93      0.93        30



# **Get Future Predictions**

In [21]:
df_new = df.sample(1)
df_new

Student_ID  CGPA   IQ  Placement
47          48   5.2  161          0

In [23]:
X_new = df_new.drop(['Student_ID' ,'Placement' ] , axis = 1)
X_new

CGPA   IQ
47   5.2  161

In [24]:
X_new = sc.fit_transform(X_new)

In [26]:
y_new_pred = lr.predict(X_new)
y_new_pred

array([0])