<a href="https://colab.research.google.com/github/pragatisachan/ProjectChalenge1/blob/main/StudentPerformance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("/content/Students Performance.csv")
df

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


In [9]:
df.describe(include = 'all')

gender race/ethnicity parental level of education     lunch  \
count     1000           1000                        1000      1000   
unique       2              5                           6         2   
top     female        group C                some college  standard   
freq       518            319                         226       645   
mean       NaN            NaN                         NaN       NaN   
std        NaN            NaN                         NaN       NaN   
min        NaN            NaN                         NaN       NaN   
25%        NaN            NaN                         NaN       NaN   
50%        NaN            NaN                         NaN       NaN   
75%        NaN            NaN                         NaN       NaN   
max        NaN            NaN                         NaN       NaN   

       test preparation course  math score  reading score  writing score  
count                     1000  1000.00000    1000.000000    1000.000000  
unique                       2         NaN            NaN            NaN  
top                       none         NaN            NaN            NaN  
freq                       642         NaN            NaN            NaN  
mean                       NaN    66.08900      69.169000      68.054000  
std                        NaN    15.16308      14.600192      15.195657  
min                        NaN     0.00000      17.000000      10.000000  
25%                        NaN    57.00000      59.000000      57.750000  
50%                        NaN    66.00000      70.000000      69.000000  
75%                        NaN    77.00000      79.000000      79.000000  
max                        NaN   100.00000     100.000000     100.000000

In [10]:
df.groupby(['race/ethnicity']).value_counts()

race/ethnicity  gender  parental level of education  lunch         test preparation course  math score  reading score  writing score
group A         female  associate's degree           free/reduced  none                     37          57             56               1
                                                                                            41          51             48               1
                male    bachelor's degree            standard      completed                75          58             62               1
                female  some high school             standard      completed                92          100            97               1
                                                                   none                     48          66             65               1
                                                                                                                                       ..
group E         female  associate's deg

In [11]:
df['test preparation course'].value_counts()

none         642
completed    358
Name: test preparation course, dtype: int64

In [12]:
df = df.replace({'test preparation course' : {'none' : 0 ,'completed' : 1 }})
df

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

     test preparation course  math score  reading score  writing score  
0                          0          72             72             74  
1                          1          69             90             88  
2                          0          90             95             93  
3                          0          47             57             44  
4                          0          76             78             75  
..                       ...         ...            ...            ...  
995                        1          88             99             95  
996                        0          62             55             55  
997                        1          59             71             65  
998                        1          68             78             77  
999                        0          77             86             86  

[1000 rows x 8 columns]

In [13]:
df = df.replace({'gender' : {'female' : 0 ,'male' : 1 }})
df

gender race/ethnicity parental level of education         lunch  \
0         0        group B           bachelor's degree      standard   
1         0        group C                some college      standard   
2         0        group B             master's degree      standard   
3         1        group A          associate's degree  free/reduced   
4         1        group C                some college      standard   
..      ...            ...                         ...           ...   
995       0        group E             master's degree      standard   
996       1        group C                 high school  free/reduced   
997       0        group C                 high school  free/reduced   
998       0        group D                some college      standard   
999       0        group D                some college  free/reduced   

     test preparation course  math score  reading score  writing score  
0                          0          72             72             74  
1                          1          69             90             88  
2                          0          90             95             93  
3                          0          47             57             44  
4                          0          76             78             75  
..                       ...         ...            ...            ...  
995                        1          88             99             95  
996                        0          62             55             55  
997                        1          59             71             65  
998                        1          68             78             77  
999                        0          77             86             86  

[1000 rows x 8 columns]

In [14]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [15]:
X = df[['gender',  'math score', 'reading score',
       'writing score']]
X

gender  math score  reading score  writing score
0         0          72             72             74
1         0          69             90             88
2         0          90             95             93
3         1          47             57             44
4         1          76             78             75
..      ...         ...            ...            ...
995       0          88             99             95
996       1          62             55             55
997       0          59             71             65
998       0          68             78             77
999       0          77             86             86

[1000 rows x 4 columns]

In [16]:
y = df['test preparation course']
y

0      0
1      1
2      0
3      0
4      0
      ..
995    1
996    0
997    1
998    1
999    0
Name: test preparation course, Length: 1000, dtype: int64

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [18]:
X = sc.fit_transform(X)
X

array([[-0.96462528,  0.39002351,  0.19399858,  0.39149181],
       [-0.96462528,  0.19207553,  1.42747598,  1.31326868],
       [-0.96462528,  1.57771141,  1.77010859,  1.64247471],
       ...,
       [-0.96462528, -0.46775108,  0.12547206, -0.20107904],
       [-0.96462528,  0.12609287,  0.60515772,  0.58901542],
       [-0.96462528,  0.71993682,  1.15336989,  1.18158627]])

In [19]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.3 , random_state = 456)
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((700, 4), (300, 4), (700,), (300,))

In [20]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train , y_train)

LogisticRegression()

In [21]:
y_pred = lr.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
from sklearn.metrics import confusion_matrix , classification_report

In [23]:
confusion_matrix(y_test , y_pred)

array([[169,  27],
       [ 61,  43]])

In [24]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.73      0.86      0.79       196
           1       0.61      0.41      0.49       104

    accuracy                           0.71       300
   macro avg       0.67      0.64      0.64       300
weighted avg       0.69      0.71      0.69       300



In [25]:
df_new = df.sample(1)
df_new

gender race/ethnicity parental level of education     lunch  \
945       0        group C          associate's degree  standard   

     test preparation course  math score  reading score  writing score  
945                        0          54             61             58

In [26]:
X_new = df_new[['gender' , 'math score' , 'reading score' , 'writing score']]
X_new

gender  math score  reading score  writing score
945       0          54             61             58

In [27]:
X_new = sc.fit_transform(X_new)


In [28]:
y_pred_new = lr.predict(X_new)
y_pred_new


array([0])